### PR TITLE
Fix hcf references, make them scf.

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ref: https://trello.com/c/ZNBu0nTv/4-5-remove-remaining-references-to-hcf-hcp
:construction: Wait with merge, this has lots of related changes, see ticket.

### CODE REVIEW

**Comment by mook-as** [comment]
I thought we were moving to `/opt/fissile` (to avoid having the product name in the path again).

**Comment by andreas-kupries** [comment]
Thank you for the reminder, will change.

**Comment by andreas-kupries** [comment]
Addressed with commit dd8fad95eaef57064b7e51c0f2bc4ef2f898a682
__Note__ Rebased.

**Review by alexjh — CHANGES_REQUESTED** [review]
`/usr/local/rvm/gems/ruby-2.3.1/gems/configgin-0.14.0/lib/job.rb:51:in `rescue in generate': failed to read template file /opt/scf/monitrc.erb`

Containers are failing to start. There seems to be a mismatch between where fissile is putting things, and where `configgin`? is expecting them. 

```bash
# find /opt
/opt
/opt/scf
/opt/scf/startup
/opt/scf/startup/scripts
/opt/scf/startup/scripts/create_mysql_data_tmp.sh
/opt/scf/startup/scripts/chown_vcap_store.sh
/opt/scf/startup/scripts/patches
/opt/scf/startup/scripts/patches/enable_mysql_galera_bootstrap.sh
/opt/scf/startup/scripts/patches/fix_mysql_advertise_ip.sh
/opt/scf/startup/scripts/patches/fix_mysql_setup_syslog_forwarder.sh
/opt/scf/startup/scripts/configure-HA-hosts.sh
/opt/scf/run.sh
/opt/scf/job_config.json
/opt/scf/share
/opt/scf/share/doc
/opt/scf/share/doc/cf-mysql
/opt/scf/share/doc/cf-mysql/LICENSE
/opt/scf/env2conf.yml
/opt/fissile
/opt/fissile/monitrc.erb
/opt/fissile/post-start.sh
```

**Comment by andreas-kupries** [comment]
Ok. Looks to be fissile, has `opt/scf` references. `configgin` does not seem to refer to `opt/` directly at all.

**Comment by andreas-kupries** [comment]
Updated fissile. See commit https://github.com/SUSE/fissile/pull/303/commits/6eed5202eb595d2a6a2ff0edd24b607570df4b65 . Now to check here for the borken path too. Then SCF and UFR.

**Comment by andreas-kupries** [comment]
It was not `configgin` referencing `/opt/fissile`, but the stemcell itself.
When checking that an unfixed use of `/opt/hcf` was found.
Corrected with commit 0e0ab7b3c90b3419e9f58ee7e9358b39b0a8a75b

**Comment by andreas-kupries** [comment]
The SCF branch needed a small change, and now has its own proper PR = https://github.com/SUSE/scf/pull/1240

**Review by alexjh — APPROVED** [review]

**Pull request merged**
